config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#index"
  get 'pages/about', as: 'about'
  get 'pages/how', as: 'how'
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard_index'

  # Pet Routes
  get 'profile', to: 'pets#profile', as: :profile
  get 'hygiene', to: 'pets#hygiene', as: :hygiene
  get 'nutrition', to: 'pets#nutrition', as: :nutrition
  get 'activities', to: 'pets#activities', as: :activities
  

  # Routes pour les vétérinaires
  resources :vets do
    resources :vet_appointments, shallow: true
  end

  # Routes imbriquées pour les pets et leurs données associées
  resources :pets do
    get 'calendar', on: :member
    resources :treatments
    resources :measurements
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        delete :remove_video
      end
    end
    resources :nutritions, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :hygienes # Ajout des routes pour les hygienes
  end

  resources :calendars, only: [:index]
  get 'calendar_events', to: 'calendars#events'
  get 'pets/:pet_id/treatments/:id/details', to: 'treatments#details'

  # Route pour les erreurs 404
  match '/404', to: 'errors#not_found', via: :all

  # Rediriger toutes les autres routes non trouvées vers la page 404
  match '*path', to: 'errors#not_found', via: :all
end

app/models/hygiene.rb
class Hygiene < ApplicationRecord
  belongs_to :pet

  enum hygiene_type: {
    groom: 1,
    teeth: 2,
    claw: 3,
    litter: 4,
    bath: 5,
    ears: 6
  }

  attribute :reminder, :datetime

  validates :hygiene_type, presence: true, inclusion: { in: hygiene_types.keys }
  validates :date, presence: true
  validates :frequency, presence: true
  validates :reminder, presence: false

  def display_hygiene_type
    hygiene_type.humanize
  end
end

app/controllers/hygiene_controller.rb
class HygieneController < ApplicationController
  # ...existing code...

  def show
    @hygiene = Hygiene.find(params[:id])
    # ...existing code...
  end

  # ...existing code...
end

app/controllers/hygienes_controller.rb
class HygienesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pet
  before_action :set_hygiene, only: [:edit, :update, :destroy]

  def index
    @hygienes = @pet.hygienes
  end

  def new
    @hygiene = @pet.hygienes.new
  end

  def create
    @hygiene = @pet.hygienes.build(hygiene_params)
    if @hygiene.save
      redirect_to pet_hygienes_path(@pet), notice: 'Hygiene successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @hygiene.update(hygiene_params)
      redirect_to pet_hygienes_path(@pet), notice: 'Hygiene successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hygiene.destroy
    redirect_to pet_hygienes_path(@pet), notice: 'Hygiene successfully deleted.'
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_hygiene
    @hygiene = @pet.hygienes.find(params[:id])
  end

  def hygiene_params
    params.require(:hygiene).permit(:hygiene_type, :date, :frequency, :note, :reminder)
  end
end

app/views/hygienes/_form.html.erb
<%= simple_form_for [@pet, @hygiene], html: { class: 'form-horizontal' } do |form| %>
  <div class="mb-4 text-center">
    <%= form.input :hygiene_type,
        collection: Hygiene.hygiene_types.keys.map { |type| [type.capitalize, type] },
        label: "<strong>Hygiene Type</strong>".html_safe,
        prompt: "Select a hygiene type",
        required: true,
        input_html: { class: "form-control text-center bg-white" } %>
  </div>

  <div class="mb-4 text-center">
    <label class="form-label">
      <strong>Date</strong>
    </label>
    <div class="input-group">
      <%= form.input :date,
          label: false,
          as: :string,
          required: true,
          wrapper: false,
          input_html: { 
            data: { controller: "datepicker" },
            class: "form-control text-center bg-white"
          } %>
      <span class="input-group-text">
        <i class="fa-regular fa-calendar"></i>
      </span>
    </div>
  </div>

  <div class="mb-4 text-center">
    <%= form.input :frequency,
        label: "<strong>Frequency</strong>".html_safe,
        as: :string,
        required: true,
        placeholder: "Ex: Once daily",
        input_html: { class: "form-control text-center bg-white" } %>
  </div>

  <div class="mb-4 text-center">
    <%= form.input :note,
        label: "<strong>Note</strong>".html_safe,
        required: false,
        input_html: { 
          class: "form-control text-center bg-white",
          rows: 3
        } %>
  </div>

  <div class="d-flex justify-content-between">
    <div class="text-center">
      <%= link_to 'Back', pet_hygienes_path(@pet), class: "btn btn-secondary rounded-pill" %>
    </div>
    <div class="text-center">
      <%= form.button :submit, form.object.new_record? ? "Add Hygiene Record" : "Update Hygiene Record", class: "btn btn-primary rounded-pill" %>
    </div>
  </div>
<% end %>

app/views/hygienes/edit.html.erb
<div data-page-name="<%= page_name %>">
  <%= render "pets/navbar_dashboard" %>
  <div class="container-fluid text-primary py-0">
    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-lg-8 mx-auto text-center">
          <h1 class="display-4 display-md-5 fw-bold mb-4">Edit Hygiene Record for <%= @pet.name %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-10 col-md-8 col-lg-6 col-xl-4 mx-auto">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hygienes/index.html.erb
<div data-page-name="<%= page_name %>">
  <%= render "pets/navbar_dashboard" %>
  <div class="container-fluid text-primary py-0">
    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-lg-8 mx-auto text-center">
          <h1 class="display-4 display-md-5 fw-bold mb-4">
            Hygiene Records for <%= @pet.name %>
          </h1>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <% if @hygienes.any? %>
            <div class="table-responsive table-card">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Type</th>
                    <th scope="col">Date</th>
                    <th scope="col">Frequency</th>
                    <th scope="col">Notes</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @hygienes.each do |hygiene| %>
                    <tr>
                      <td class="text-capitalize"><%= hygiene.hygiene_type %></td>
                      <td><%= hygiene.date.strftime("%B %d, %Y") %></td>
                      <td><%= hygiene.frequency.present? ? hygiene.frequency : 'N/A' %></td>
                      <td><%= hygiene.note %></td>
                      <td>
                        <%= link_to edit_pet_hygiene_path(@pet, hygiene), class: "btn btn-sm btn-outline-primary me-2" do %>
                          <i class="fa-regular fa-pen-to-square"></i>
                        <% end %>
                        <%= link_to pet_hygiene_path(@pet, hygiene),
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                            class: "btn btn-sm btn-outline-danger" do %>
                          <i class="fa-regular fa-trash-can"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% else %>
            <div class="text-center py-5">
              <p class="mb-4">No hygiene records yet.</p>
            </div>
          <% end %>
          <div class="d-flex justify-content-center gap-4 mt-4">
            <div class="text-center">
              <%= link_to 'Back', pet_path(@pet), class: "btn btn-secondary rounded-pill" %>
            </div>
            <div class="text-center">
              <%= link_to new_pet_hygiene_path(@pet), class: "btn btn-primary rounded-pill" do %>
                <i class="fa-solid fa-plus me-2"></i>Add Hygiene Record
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hygienes/new.html.erb
<div data-page-name="<%= page_name %>">
  <%= render "pets/navbar_dashboard" %>
  <div class="container-fluid text-primary py-0">
    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-lg-8 mx-auto text-center">
          <h1 class="display-4 display-md-5 fw-bold mb-4">Add a new hygiene record for <%= @pet.name %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-10 col-md-8 col-lg-6 col-xl-4 mx-auto">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>