config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#index"
  get 'pages/about', as: 'about'
  get 'pages/how', as: 'how'
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard_index'

  # Pet Routes
  get 'profile', to: 'pets#profile', as: :profile
  get 'hygiene', to: 'pets#hygiene', as: :hygiene
  get 'nutrition', to: 'pets#nutrition', as: :nutrition
  get 'activities', to: 'pets#activities', as: :activities
  

  # Routes pour les vétérinaires
  resources :vets do
    resources :vet_appointments, shallow: true
  end

  # Routes imbriquées pour les pets et leurs données associées
  resources :pets do
    get 'calendar', on: :member
    resources :treatments
    resources :measurements
    resources :activities, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        delete :remove_video
      end
    end
    resources :nutritions, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :hygienes # Ajout des routes pour les hygienes
  end

  resources :calendars, only: [:index]
  get 'calendar_events', to: 'calendars#events'
  get 'pets/:pet_id/treatments/:id/details', to: 'treatments#details'

  # Route pour les erreurs 404
  match '/404', to: 'errors#not_found', via: :all

  # Rediriger toutes les autres routes non trouvées vers la page 404
  match '*path', to: 'errors#not_found', via: :all
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :pet
  has_one_attached :video

  TRAINING_TYPES = ['Sit', 'Stay', 'Roll over', 'Heel']

  validates :training_type, inclusion: { in: TRAINING_TYPES }

  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

  def correct_video_mime_type
    if video.attached? && !video.content_type.in?(%w[video/mp4 video/quicktime video/mpeg video/avi])
      errors.add(:video, 'must be a valid video format (mp4, quicktime, mpeg, avi)')
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_pet
  before_action :set_activity, only: [:edit, :update, :destroy, :remove_video] # ajout de remove_video ici
  
  def remove_video
    @activity.video.purge
    redirect_to edit_pet_activity_path(@pet, @activity), notice: 'Video was successfully removed.'
  end

  def index
    @activities = @pet.activities
  end

  def new
    @activity = @pet.activities.new
  end

  def create
    @activity = @pet.activities.new(activity_params)
    if @activity.save
      redirect_to pet_activities_path(@pet), notice: 'Activity added successfully!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to pet_activities_path(@pet), notice: 'Activity updated successfully!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity.destroy
    redirect_to pet_activities_path(@pet), notice: 'Activity deleted successfully!'
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_activity
    @activity = @pet.activities.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:training_type, :rating, :notes, :video)
  end
end

app/views/activities/_form.html.erb
<%= render "pets/navbar_dashboard" %>
<div class="container-fluid text-primary py-0">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-lg-8 mx-auto text-center">
        <h1 class="display-4 display-md-5 fw-bold mb-4">Add a new activity for <%= @pet.name %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-10 col-md-8 col-lg-6 col-xl-4 mx-auto">
        <%= form_with model: [@pet, @activity], local: true, authenticity_token: true, html: { class: 'form-horizontal' } do |form| %>
          <div class="mb-4 text-center">
            <%= form.label :training_type, "<strong>Training Type</strong>".html_safe, class: "form-label" %>
            <%= form.select :training_type, Activity::TRAINING_TYPES, { prompt: "Select Training Type" }, class: "form-select text-center bg-white" %>
          </div>

          <div class="mb-4 text-center">
            <%= form.label :rating, "<strong>Rating (1-10)</strong>".html_safe, class: "form-label" %>
            <%= form.number_field :rating, min: 1, max: 10, required: true, class: "form-control text-center bg-white" %>
          </div>

          <div class="mb-4 text-center">
            <%= form.label :notes, "<strong>Notes</strong>".html_safe, class: "form-label" %>
            <%= form.text_area :notes, rows: 3, class: "form-control text-center bg-white" %>
          </div>

          <div class="mb-4 text-center">
            <%= form.label :video, "<strong>Upload Video</strong>".html_safe, class: "form-label" %>
            <%= form.file_field :video, class: "form-control text-center bg-white" %>
          </div>

          <div class="d-flex justify-content-between">
            <div class="text-center">
              <%= link_to 'Cancel', pet_path(@pet), class: "btn btn-secondary rounded-pill" %>
            </div>
            <div class="text-center">
              <%= form.submit "Save Training Log", class: "btn btn-primary rounded-pill" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<div data-page-name="<%= page_name %>">
  <%= render "pets/navbar_dashboard" %>
  <div class="container-fluid text-primary py-0">
	<div class="container py-5">
	  <div class="row">
		<div class="col-12 col-lg-8 mx-auto text-center">
		  <h1 class="display-4 display-md-5 fw-bold mb-4">Modify activity for <%= @pet.name %></h1>
		</div>
	  </div>
	  <div class="row">
		<div class="col-10 col-md-8 col-lg-6 col-xl-4 mx-auto">
		  <%= form_with model: [@pet, @activity], local: true, authenticity_token: true, html: { class: 'form-horizontal' } do |form| %>
			<div class="mb-4 text-center">
			  <%= form.label :training_type, "<strong>Training Type</strong>".html_safe, class: "form-label" %>
			  <%= form.select :training_type, Activity::TRAINING_TYPES, { prompt: "Select Training Type" }, class: "form-select text-center bg-white" %>
			</div>

			<div class="mb-4 text-center">
			  <%= form.label :rating, "<strong>Rating (1-10)</strong>".html_safe, class: "form-label" %>
			  <%= form.number_field :rating, min: 1, max: 10, required: true, class: "form-control text-center bg-white" %>
			</div>

			<div class="mb-4 text-center">
			  <%= form.label :notes, "<strong>Notes</strong>".html_safe, class: "form-label" %>
			  <%= form.text_area :notes, rows: 3, class: "form-control text-center bg-white" %>
			</div>

			<div class="mb-4 text-center">
			  <% if @activity.video.attached? %>
				<div class="mb-3">
				  <p><strong>Current Video</strong></p>
				  <%= cl_video_tag @activity.video.key, 
					controls: true,
					width: 300,
					height: 200,
					crop: :fill,
					gravity: :center,
					resource_type: :video,
					class: "rounded shadow mb-2"
				  %>
				  <div class="mt-2">
					<%= link_to "Remove Video", remove_video_pet_activity_path(@pet, @activity), 
						class: "btn btn-danger btn-sm rounded-pill",
						data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this video?" } %>
				  </div>
				</div>
			  <% end %>
			  <%= form.label :video, "<strong>Upload Video</strong>".html_safe, class: "form-label" %>
			  <%= form.file_field :video, class: "form-control text-center bg-white" %>
			</div>

			<div class="d-flex justify-content-between">
			  <div class="text-center">
				<%= link_to 'Cancel', pet_path(@pet), class: "btn btn-secondary rounded-pill" %>
			  </div>
			  <div class="text-center">
				<%= form.submit "Modify activity", class: "btn btn-primary rounded-pill" %>
			  </div>
			</div>
		  <% end %>
		</div>
	  </div>
	</div>
  </div>
</div>

app/views/activities/index.html.erb
<div data-page-name="<%= page_name %>">
  <%= render "pets/navbar_dashboard" %>
  <div class="container-fluid text-primary py-0">
    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-lg-8 mx-auto text-center">
          <h1 class="display-4 display-md-5 fw-bold mb-4">
            Training Activities for <%= @pet.name %>
          </h1>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <% if @activities.any? %>
            <div class="table-responsive table-card">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Training</th>
                    <th scope="col">Rating</th>
                    <th scope="col">Notes</th>
                    <th scope="col">Video</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @activities.each do |activity| %>
                    <tr>
                      <td class="text-capitalize"><%= activity.training_type %></td>
                      <td><%= activity.rating %></td>
                      <td><%= activity.notes %></td>
                      <td>
                        <% if activity.video.attached? %>
                          <div class="video-container" data-controller="expandable">
                            <button class="btn btn-sm btn-outline-primary expand-button" data-action="click->expandable#toggle">Expand</button>
                            <div class="video-content">
                              <%= cl_video_tag activity.video.key, controls: true, width: 300 %>
                            </div>
                          </div>
                        <% else %>
                          <p>No video uploaded</p>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to edit_pet_activity_path(@pet, activity), class: "btn btn-sm btn-outline-primary me-2" do %>
                          <i class="fa-regular fa-pen-to-square"></i>
                        <% end %>
                        <%= link_to pet_activity_path(@pet, activity),
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                            class: "btn btn-sm btn-outline-danger" do %>
                          <i class="fa-regular fa-trash-can"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% else %>
            <div class="text-center py-5">
              <p class="mb-4">No activities recorded yet.</p>
            </div>
          <% end %>

          <div class="d-flex justify-content-center gap-4 mt-4">
            <div class="text-center">
              <%= link_to 'Back', pet_path(@pet), class: "btn btn-secondary rounded-pill" %>
            </div>
            <%= link_to new_pet_activity_path(@pet), class: "btn btn-primary rounded-pill" do %>
              <i class="fa-solid fa-plus me-2"></i>Log a New Activity
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div data-page-name="<%= page_name %>">
	<%= render "pets/navbar_dashboard" %>
	<div class="container-fluid text-primary py-0">
	  <div class="container py-5">
		<div class="row">
		  <div class="col-12 col-lg-8 mx-auto text-center">
			<h1 class="display-4 display-md-5 fw-bold mb-4">Add a new activity for <%= @pet.name %></h1>
		  </div>
		</div>
		<div class="row">
		  <div class="col-10 col-md-8 col-lg-6 col-xl-4 mx-auto">
			<%= form_with model: [@pet, @activity], local: true, authenticity_token: true, html: { class: 'form-horizontal' } do |form| %>
			  <div class="mb-4 text-center">
				<%= form.label :training_type, "<strong>Training Type</strong>".html_safe, class: "form-label" %>
				<%= form.select :training_type, Activity::TRAINING_TYPES, { prompt: "Select Training Type" }, class: "form-select text-center bg-white" %>
			  </div>
	
			  <div class="mb-4 text-center">
				<%= form.label :rating, "<strong>Rating (1-10)</strong>".html_safe, class: "form-label" %>
				<%= form.number_field :rating, min: 1, max: 10, required: true, class: "form-control text-center bg-white" %>
			  </div>
	
			  <div class="mb-4 text-center">
				<%= form.label :notes, "<strong>Notes</strong>".html_safe, class: "form-label" %>
				<%= form.text_area :notes, rows: 3, class: "form-control text-center bg-white" %>
			  </div>
	
			  <div class="mb-4 text-center">
				<%= form.label :video, "<strong>Upload Video</strong>".html_safe, class: "form-label" %>
				<%= form.file_field :video, class: "form-control text-center bg-white" %>
			  </div>
	
			  <div class="d-flex justify-content-between">
				<div class="text-center">
				  <%= link_to 'Cancel', pet_path(@pet), class: "btn btn-secondary rounded-pill" %>
				</div>
				<div class="text-center">
				  <%= form.submit "Save Training Log", class: "btn btn-primary rounded-pill" %>
				</div>
			  </div>
			<% end %>
		  </div>
		</div>
	  </div>
	</div>
</div>